export const SUCCESS_EXIT_CODE = 0
export const ERROR_EXIT_CODE = 1
export const SHELL_BUILTIN_EXIT_CODE = 2
export const COMMAND_INVOKED_CANNOT_EXECUTE_EXIT_CODE = 126
export const COMMAND_NOT_FOUND_EXIT_CODE = 127
